apiVersion: v1
kind: PersistentVolume
metadata:
  name: reids-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/redis-data-pv
